// ============================================================
//  DATA.JS — כל תוכן השיעורים
//  להוספת נושא חדש, פשוט העתק/י בלוק קיים ושנה/י את הנתונים!
// ============================================================

// ─────────────────────────────────────────
//  האלפבית
// ─────────────────────────────────────────
const alphabet = [
  {L:'A',l:'a',w:'Apple',emoji:'🍎'},
  {L:'B',l:'b',w:'Ball',emoji:'⚽'},
  {L:'C',l:'c',w:'Cat',emoji:'🐱'},
  {L:'D',l:'d',w:'Dog',emoji:'🐶'},
  {L:'E',l:'e',w:'Egg',emoji:'🥚'},
  {L:'F',l:'f',w:'Fish',emoji:'🐟'},
  {L:'G',l:'g',w:'Goat',emoji:'🐐'},
  {L:'H',l:'h',w:'Hat',emoji:'🎩'},
  {L:'I',l:'i',w:'Ice',emoji:'🧊'},
  {L:'J',l:'j',w:'Jam',emoji:'🍓'},
  {L:'K',l:'k',w:'Kite',emoji:'🪁'},
  {L:'L',l:'l',w:'Lion',emoji:'🦁'},
  {L:'M',l:'m',w:'Moon',emoji:'🌙'},
  {L:'N',l:'n',w:'Nest',emoji:'🪺'},
  {L:'O',l:'o',w:'Orange',emoji:'🍊'},
  {L:'P',l:'p',w:'Pen',emoji:'✏️'},
  {L:'Q',l:'q',w:'Queen',emoji:'👑'},
  {L:'R',l:'r',w:'Rain',emoji:'🌧️'},
  {L:'S',l:'s',w:'Sun',emoji:'☀️'},
  {L:'T',l:'t',w:'Tree',emoji:'🌳'},
  {L:'U',l:'u',w:'Umbrella',emoji:'☂️'},
  {L:'V',l:'v',w:'Van',emoji:'🚐'},
  {L:'W',l:'w',w:'Water',emoji:'💧'},
  {L:'X',l:'x',w:'Box',emoji:'📦'},
  {L:'Y',l:'y',w:'Yo-yo',emoji:'🪀'},
  {L:'Z',l:'z',w:'Zebra',emoji:'🦓'},
];

// ─────────────────────────────────────────
//  נושאי אוצר מילים
//  כל נושא: id, title, emoji, color, words[]
//  כל מילה: en (אנגלית), he (עברית), emoji
// ─────────────────────────────────────────
const vocabTopics = [
  {
    id: 'numbers1',
    title: 'מספרים 1–10',
    emoji: '🔢',
    color: '#4FC3F7',
    words: [
      {en:'One',   he:'אחד',   emoji:'1️⃣'},
      {en:'Two',   he:'שתיים', emoji:'2️⃣'},
      {en:'Three', he:'שלוש',  emoji:'3️⃣'},
      {en:'Four',  he:'ארבע',  emoji:'4️⃣'},
      {en:'Five',  he:'חמש',   emoji:'5️⃣'},
      {en:'Six',   he:'שש',    emoji:'6️⃣'},
      {en:'Seven', he:'שבע',   emoji:'7️⃣'},
      {en:'Eight', he:'שמונה', emoji:'8️⃣'},
      {en:'Nine',  he:'תשע',   emoji:'9️⃣'},
      {en:'Ten',   he:'עשר',   emoji:'🔟'},
    ]
  },
  {
    id: 'numbers2',
    title: 'מספרים 11–20',
    emoji: '🔣',
    color: '#29B6F6',
    words: [
      {en:'Eleven',    he:'אחד עשר',   emoji:'1️⃣1️⃣'},
      {en:'Twelve',    he:'שנים עשר',  emoji:'1️⃣2️⃣'},
      {en:'Thirteen',  he:'שלוש עשרה', emoji:'1️⃣3️⃣'},
      {en:'Fourteen',  he:'ארבע עשרה', emoji:'1️⃣4️⃣'},
      {en:'Fifteen',   he:'חמש עשרה',  emoji:'1️⃣5️⃣'},
      {en:'Sixteen',   he:'שש עשרה',   emoji:'1️⃣6️⃣'},
      {en:'Seventeen', he:'שבע עשרה',  emoji:'1️⃣7️⃣'},
      {en:'Eighteen',  he:'שמונה עשרה',emoji:'1️⃣8️⃣'},
      {en:'Nineteen',  he:'תשע עשרה',  emoji:'1️⃣9️⃣'},
      {en:'Twenty',    he:'עשרים',     emoji:'2️⃣0️⃣'},
    ]
  },
  {
    id: 'numbers3',
    title: 'עשרות',
    emoji: '💯',
    color: '#0288D1',
    words: [
      {en:'Ten',     he:'עשר',    emoji:'🔟'},
      {en:'Twenty',  he:'עשרים',  emoji:'✌️'},
      {en:'Thirty',  he:'שלושים', emoji:'3️⃣0️⃣'},
      {en:'Forty',   he:'ארבעים', emoji:'4️⃣0️⃣'},
      {en:'Fifty',   he:'חמישים', emoji:'5️⃣0️⃣'},
      {en:'Sixty',   he:'שישים',  emoji:'6️⃣0️⃣'},
      {en:'Seventy', he:'שבעים',  emoji:'7️⃣0️⃣'},
      {en:'Eighty',  he:'שמונים', emoji:'8️⃣0️⃣'},
      {en:'Ninety',  he:'תשעים',  emoji:'9️⃣0️⃣'},
      {en:'Hundred', he:'מאה',    emoji:'💯'},
    ]
  },
  {
    id: 'animals',
    title: 'חיות',
    emoji: '🐾',
    color: '#66BB6A',
    words: [
      {en:'Cat',       he:'חתול',  emoji:'🐱'},
      {en:'Dog',       he:'כלב',   emoji:'🐶'},
      {en:'Bird',      he:'ציפור', emoji:'🐦'},
      {en:'Fish',      he:'דג',    emoji:'🐟'},
      {en:'Rabbit',    he:'ארנב',  emoji:'🐰'},
      {en:'Horse',     he:'סוס',   emoji:'🐴'},
      {en:'Cow',       he:'פרה',   emoji:'🐮'},
      {en:'Lion',      he:'אריה',  emoji:'🦁'},
      {en:'Elephant',  he:'פיל',   emoji:'🐘'},
      {en:'Butterfly', he:'פרפר',  emoji:'🦋'},
    ]
  },
  {
    id: 'animals2',
    title: 'עוד חיות',
    emoji: '🦁',
    color: '#43A047',
    words: [
      {en:'Tiger',    he:'נמר',    emoji:'🐯'},
      {en:'Monkey',   he:'קוף',    emoji:'🐒'},
      {en:'Penguin',  he:'פינגווין',emoji:'🐧'},
      {en:'Duck',     he:'ברווז',  emoji:'🦆'},
      {en:'Frog',     he:'צפרדע', emoji:'🐸'},
      {en:'Snake',    he:'נחש',    emoji:'🐍'},
      {en:'Bear',     he:'דוב',    emoji:'🐻'},
      {en:'Giraffe',  he:'ג\'ירפה',emoji:'🦒'},
      {en:'Zebra',    he:'זברה',   emoji:'🦓'},
      {en:'Turtle',   he:'צב',     emoji:'🐢'},
    ]
  },
  {
    id: 'aroundme',
    title: 'סביבתי',
    emoji: '🏠',
    color: '#FFA726',
    words: [
      {en:'Table',  he:'שולחן', emoji:'🪑'},
      {en:'Chair',  he:'כיסא',  emoji:'💺'},
      {en:'Bed',    he:'מיטה',  emoji:'🛏️'},
      {en:'Door',   he:'דלת',   emoji:'🚪'},
      {en:'Window', he:'חלון',  emoji:'🪟'},
      {en:'Book',   he:'ספר',   emoji:'📚'},
      {en:'Bag',    he:'תיק',   emoji:'🎒'},
      {en:'Ball',   he:'כדור',  emoji:'⚽'},
      {en:'Cup',    he:'כוס',   emoji:'🥤'},
      {en:'Pencil', he:'עיפרון',emoji:'✏️'},
    ]
  },
  {
    id: 'clothes',
    title: 'בגדים',
    emoji: '👕',
    color: '#EC407A',
    words: [
      {en:'Shirt',   he:'חולצה',  emoji:'👕'},
      {en:'Pants',   he:'מכנסיים',emoji:'👖'},
      {en:'Dress',   he:'שמלה',   emoji:'👗'},
      {en:'Shoes',   he:'נעליים', emoji:'👟'},
      {en:'Hat',     he:'כובע',   emoji:'🎩'},
      {en:'Socks',   he:'גרביים', emoji:'🧦'},
      {en:'Coat',    he:'מעיל',   emoji:'🧥'},
      {en:'Gloves',  he:'כפפות',  emoji:'🧤'},
      {en:'Scarf',   he:'צעיף',   emoji:'🧣'},
      {en:'Pajamas', he:'פיג\'מה',emoji:'🛌'},
    ]
  },
  {
    id: 'colors',
    title: 'צבעים',
    emoji: '🎨',
    color: '#AB47BC',
    words: [
      {en:'Red',    he:'אדום',  emoji:'🔴'},
      {en:'Blue',   he:'כחול',  emoji:'🔵'},
      {en:'Green',  he:'ירוק',  emoji:'🟢'},
      {en:'Yellow', he:'צהוב',  emoji:'🟡'},
      {en:'Orange', he:'כתום',  emoji:'🟠'},
      {en:'Purple', he:'סגול',  emoji:'🟣'},
      {en:'Pink',   he:'ורוד',  emoji:'🩷'},
      {en:'White',  he:'לבן',   emoji:'⬜'},
      {en:'Black',  he:'שחור',  emoji:'⬛'},
      {en:'Brown',  he:'חום',   emoji:'🟫'},
    ]
  },
  {
    id: 'food',
    title: 'אוכל',
    emoji: '🍔',
    color: '#FF7043',
    words: [
      {en:'Apple',  he:'תפוח',   emoji:'🍎'},
      {en:'Banana', he:'בננה',   emoji:'🍌'},
      {en:'Bread',  he:'לחם',    emoji:'🍞'},
      {en:'Milk',   he:'חלב',    emoji:'🥛'},
      {en:'Egg',    he:'ביצה',   emoji:'🥚'},
      {en:'Pizza',  he:'פיצה',   emoji:'🍕'},
      {en:'Water',  he:'מים',    emoji:'💧'},
      {en:'Cake',   he:'עוגה',   emoji:'🎂'},
      {en:'Cheese', he:'גבינה',  emoji:'🧀'},
      {en:'Cookie', he:'עוגייה', emoji:'🍪'},
    ]
  },
  {
    id: 'food2',
    title: 'עוד אוכל',
    emoji: '🥗',
    color: '#EF5350',
    words: [
      {en:'Rice',       he:'אורז',   emoji:'🍚'},
      {en:'Soup',       he:'מרק',    emoji:'🍲'},
      {en:'Salad',      he:'סלט',    emoji:'🥗'},
      {en:'Chicken',    he:'עוף',    emoji:'🍗'},
      {en:'Ice cream',  he:'גלידה',  emoji:'🍦'},
      {en:'Chocolate',  he:'שוקולד', emoji:'🍫'},
      {en:'Strawberry', he:'תות',    emoji:'🍓'},
      {en:'Watermelon', he:'אבטיח',  emoji:'🍉'},
      {en:'Grapes',     he:'ענבים',  emoji:'🍇'},
      {en:'Carrot',     he:'גזר',    emoji:'🥕'},
    ]
  },
  {
    id: 'body',
    title: 'חלקי גוף',
    emoji: '🙋',
    color: '#26C6DA',
    words: [
      {en:'Head',   he:'ראש',    emoji:'🗣️'},
      {en:'Eye',    he:'עין',    emoji:'👁️'},
      {en:'Nose',   he:'אף',     emoji:'👃'},
      {en:'Mouth',  he:'פה',     emoji:'👄'},
      {en:'Ear',    he:'אוזן',   emoji:'👂'},
      {en:'Hand',   he:'יד',     emoji:'✋'},
      {en:'Foot',   he:'רגל',    emoji:'🦶'},
      {en:'Hair',   he:'שיער',   emoji:'💇'},
      {en:'Teeth',  he:'שיניים', emoji:'🦷'},
      {en:'Belly',  he:'בטן',    emoji:'🫃'},
    ]
  },
  {
    id: 'school',
    title: 'בית ספר',
    emoji: '🏫',
    color: '#7E57C2',
    words: [
      {en:'Teacher',  he:'מורה',     emoji:'👩‍🏫'},
      {en:'Student',  he:'תלמיד',    emoji:'🧒'},
      {en:'Pencil',   he:'עיפרון',   emoji:'✏️'},
      {en:'Pen',      he:'עט',       emoji:'🖊️'},
      {en:'Notebook', he:'מחברת',    emoji:'📓'},
      {en:'Ruler',    he:'סרגל',     emoji:'📏'},
      {en:'Eraser',   he:'מחק',      emoji:'🧹'},
      {en:'Scissors', he:'מספריים',  emoji:'✂️'},
      {en:'Desk',     he:'שולחן',    emoji:'🪑'},
      {en:'Blackboard',he:'לוח',     emoji:'🖊️'},
    ]
  },
  {
    id: 'nature',
    title: 'טבע',
    emoji: '🌿',
    color: '#26A69A',
    words: [
      {en:'Sun',    he:'שמש',  emoji:'☀️'},
      {en:'Moon',   he:'ירח',  emoji:'🌙'},
      {en:'Star',   he:'כוכב', emoji:'⭐'},
      {en:'Cloud',  he:'ענן',  emoji:'☁️'},
      {en:'Rain',   he:'גשם',  emoji:'🌧️'},
      {en:'Tree',   he:'עץ',   emoji:'🌳'},
      {en:'Flower', he:'פרח',  emoji:'🌸'},
      {en:'River',  he:'נהר',  emoji:'🌊'},
      {en:'Mountain',he:'הר',  emoji:'⛰️'},
      {en:'Sea',    he:'ים',   emoji:'🌊'},
    ]
  },
  {
    id: 'family',
    title: 'משפחה',
    emoji: '👨‍👩‍👧',
    color: '#F06292',
    words: [
      {en:'Mom',         he:'אמא',    emoji:'👩'},
      {en:'Dad',         he:'אבא',    emoji:'👨'},
      {en:'Brother',     he:'אח',     emoji:'👦'},
      {en:'Sister',      he:'אחות',   emoji:'👧'},
      {en:'Grandma',     he:'סבתא',   emoji:'👵'},
      {en:'Grandpa',     he:'סבא',    emoji:'👴'},
      {en:'Baby',        he:'תינוק',  emoji:'👶'},
      {en:'Friend',      he:'חבר',    emoji:'🤝'},
      {en:'Uncle',       he:'דוד',    emoji:'🧑'},
      {en:'Aunt',        he:'דודה',   emoji:'👩'},
    ]
  },
  {
    id: 'transport',
    title: 'תחבורה',
    emoji: '🚗',
    color: '#FF8F00',
    words: [
      {en:'Car',        he:'מכונית', emoji:'🚗'},
      {en:'Bus',        he:'אוטובוס',emoji:'🚌'},
      {en:'Train',      he:'רכבת',   emoji:'🚂'},
      {en:'Airplane',   he:'מטוס',   emoji:'✈️'},
      {en:'Bicycle',    he:'אופניים',emoji:'🚲'},
      {en:'Boat',       he:'סירה',   emoji:'⛵'},
      {en:'Truck',      he:'משאית',  emoji:'🚚'},
      {en:'Motorcycle', he:'אופנוע', emoji:'🏍️'},
      {en:'Helicopter', he:'מסוק',   emoji:'🚁'},
      {en:'Rocket',     he:'טיל',    emoji:'🚀'},
    ]
  },
  {
    id: 'sports',
    title: 'ספורט',
    emoji: '⚽',
    color: '#43A047',
    words: [
      {en:'Soccer',     he:'כדורגל',  emoji:'⚽'},
      {en:'Basketball', he:'כדורסל',  emoji:'🏀'},
      {en:'Swimming',   he:'שחייה',   emoji:'🏊'},
      {en:'Running',    he:'ריצה',    emoji:'🏃'},
      {en:'Tennis',     he:'טניס',    emoji:'🎾'},
      {en:'Volleyball', he:'כדורעף',  emoji:'🏐'},
      {en:'Cycling',    he:'רכיבה על אופניים', emoji:'🚴'},
      {en:'Gymnastics', he:'התעמלות', emoji:'🤸'},
      {en:'Dancing',    he:'ריקוד',   emoji:'💃'},
      {en:'Jumping',    he:'קפיצה',   emoji:'🦘'},
    ]
  },
  {
    id: 'fruits',
    title: 'פירות',
    emoji: '🍓',
    color: '#E53935',
    words: [
      {en:'Apple',      he:'תפוח',    emoji:'🍎'},
      {en:'Banana',     he:'בננה',    emoji:'🍌'},
      {en:'Orange',     he:'תפוז',    emoji:'🍊'},
      {en:'Strawberry', he:'תות',     emoji:'🍓'},
      {en:'Grapes',     he:'ענבים',   emoji:'🍇'},
      {en:'Watermelon', he:'אבטיח',   emoji:'🍉'},
      {en:'Mango',      he:'מנגו',    emoji:'🥭'},
      {en:'Pear',       he:'אגס',     emoji:'🍐'},
      {en:'Peach',      he:'אפרסק',   emoji:'🍑'},
      {en:'Lemon',      he:'לימון',   emoji:'🍋'},
    ]
  },
  {
    id: 'vegetables',
    title: 'ירקות',
    emoji: '🥦',
    color: '#2E7D32',
    words: [
      {en:'Carrot',     he:'גזר',     emoji:'🥕'},
      {en:'Tomato',     he:'עגבנייה', emoji:'🍅'},
      {en:'Cucumber',   he:'מלפפון',  emoji:'🥒'},
      {en:'Corn',       he:'תירס',    emoji:'🌽'},
      {en:'Broccoli',   he:'ברוקולי', emoji:'🥦'},
      {en:'Potato',     he:'תפוח אדמה',emoji:'🥔'},
      {en:'Onion',      he:'בצל',     emoji:'🧅'},
      {en:'Garlic',     he:'שום',     emoji:'🧄'},
      {en:'Pepper',     he:'פלפל',    emoji:'🫑'},
      {en:'Lettuce',    he:'חסה',     emoji:'🥬'},
    ]
  },
  {
    id: 'toys',
    title: 'צעצועים',
    emoji: '🧸',
    color: '#F06292',
    words: [
      {en:'Teddy bear',  he:'דובי',       emoji:'🧸'},
      {en:'Doll',        he:'בובה',       emoji:'🪆'},
      {en:'Ball',        he:'כדור',       emoji:'⚽'},
      {en:'Blocks',      he:'קוביות',     emoji:'🧱'},
      {en:'Puzzle',      he:'פאזל',       emoji:'🧩'},
      {en:'Kite',        he:'עפיפון',     emoji:'🪁'},
      {en:'Yo-yo',       he:'יויו',       emoji:'🪀'},
      {en:'Robot',       he:'רובוט',      emoji:'🤖'},
      {en:'Balloon',     he:'בלון',       emoji:'🎈'},
      {en:'Board game',  he:'משחק קופסה', emoji:'🎲'},
    ]
  },
  {
    id: 'rooms',
    title: 'חדרים בבית',
    emoji: '🏠',
    color: '#8D6E63',
    words: [
      {en:'Bedroom',    he:'חדר שינה',  emoji:'🛏️'},
      {en:'Bathroom',   he:'חדר אמבטיה',emoji:'🛁'},
      {en:'Kitchen',    he:'מטבח',      emoji:'🍳'},
      {en:'Living room',he:'סלון',      emoji:'🛋️'},
      {en:'Garden',     he:'גינה',      emoji:'🌿'},
      {en:'Balcony',    he:'מרפסת',     emoji:'🏗️'},
      {en:'Garage',     he:'מוסך',      emoji:'🚗'},
      {en:'Stairs',     he:'מדרגות',    emoji:'🪜'},
      {en:'Hallway',    he:'מסדרון',    emoji:'🚪'},
      {en:'Roof',       he:'גג',        emoji:'🏠'},
    ]
  },
  {
    id: 'feelings',
    title: 'רגשות',
    emoji: '😊',
    color: '#FFB300',
    words: [
      {en:'Happy',    he:'שמח',    emoji:'😄'},
      {en:'Sad',      he:'עצוב',   emoji:'😢'},
      {en:'Angry',    he:'כועס',   emoji:'😡'},
      {en:'Scared',   he:'מפחד',   emoji:'😱'},
      {en:'Surprised',he:'מופתע',  emoji:'😲'},
      {en:'Excited',  he:'נרגש',   emoji:'🤩'},
      {en:'Tired',    he:'עייף',   emoji:'😴'},
      {en:'Bored',    he:'משועמם', emoji:'😑'},
      {en:'Proud',    he:'גאה',    emoji:'😤'},
      {en:'Shy',      he:'ביישן',  emoji:'😳'},
    ]
  },
  {
    id: 'shapes',
    title: 'צורות',
    emoji: '🔷',
    color: '#1565C0',
    words: [
      {en:'Circle',    he:'עיגול',    emoji:'⭕'},
      {en:'Square',    he:'ריבוע',    emoji:'🟥'},
      {en:'Triangle',  he:'משולש',    emoji:'🔺'},
      {en:'Rectangle', he:'מלבן',     emoji:'▬'},
      {en:'Star',      he:'כוכב',     emoji:'⭐'},
      {en:'Heart',     he:'לב',       emoji:'❤️'},
      {en:'Diamond',   he:'מעוין',    emoji:'🔷'},
      {en:'Oval',      he:'אליפסה',   emoji:'🥚'},
      {en:'Arrow',     he:'חץ',       emoji:'➡️'},
      {en:'Cross',     he:'צלב',      emoji:'✝️'},
    ]
  },
  {
    id: 'weather',
    title: 'מזג אוויר',
    emoji: '🌤️',
    color: '#039BE5',
    words: [
      {en:'Sunny',    he:'שמשי',   emoji:'☀️'},
      {en:'Cloudy',   he:'מעונן',  emoji:'☁️'},
      {en:'Rainy',    he:'גשום',   emoji:'🌧️'},
      {en:'Windy',    he:'סוער',   emoji:'💨'},
      {en:'Snowy',    he:'מושלג',  emoji:'❄️'},
      {en:'Foggy',    he:'ערפילי', emoji:'🌫️'},
      {en:'Thunder',  he:'רעם',    emoji:'⛈️'},
      {en:'Rainbow',  he:'קשת',    emoji:'🌈'},
      {en:'Hot',      he:'חם',     emoji:'🥵'},
      {en:'Cold',     he:'קר',     emoji:'🥶'},
    ]
  },
  {
    id: 'seasons',
    title: 'עונות השנה',
    emoji: '🍂',
    color: '#E65100',
    words: [
      {en:'Spring',  he:'אביב',  emoji:'🌸'},
      {en:'Summer',  he:'קיץ',   emoji:'☀️'},
      {en:'Autumn',  he:'סתיו',  emoji:'🍂'},
      {en:'Winter',  he:'חורף',  emoji:'❄️'},
      {en:'Hot',     he:'חם',    emoji:'🥵'},
      {en:'Warm',    he:'חמים',  emoji:'🌤️'},
      {en:'Cool',    he:'קריר',  emoji:'🍃'},
      {en:'Cold',    he:'קר',    emoji:'🧊'},
      {en:'Sunny',   he:'שמשי',  emoji:'🌞'},
      {en:'Rainy',   he:'גשום',  emoji:'🌧️'},
    ]
  },
  {
    id: 'days',
    title: 'ימי השבוע',
    emoji: '📅',
    color: '#6A1B9A',
    words: [
      {en:'Sunday',    he:'יום ראשון',  emoji:'1️⃣'},
      {en:'Monday',    he:'יום שני',    emoji:'2️⃣'},
      {en:'Tuesday',   he:'יום שלישי',  emoji:'3️⃣'},
      {en:'Wednesday', he:'יום רביעי',  emoji:'4️⃣'},
      {en:'Thursday',  he:'יום חמישי',  emoji:'5️⃣'},
      {en:'Friday',    he:'יום שישי',   emoji:'6️⃣'},
      {en:'Saturday',  he:'שבת',        emoji:'✡️'},
      {en:'Weekend',   he:'סוף שבוע',   emoji:'🎉'},
      {en:'Today',     he:'היום',       emoji:'📆'},
      {en:'Tomorrow',  he:'מחר',        emoji:'⏭️'},
    ]
  },
  {
    id: 'sea_animals',
    title: 'חיות ים',
    emoji: '🐟',
    color: '#0277BD',
    words: [
      {en:'Fish',      he:'דג',        emoji:'🐟'},
      {en:'Shark',     he:'כריש',      emoji:'🦈'},
      {en:'Dolphin',   he:'דולפין',    emoji:'🐬'},
      {en:'Whale',     he:'לווייתן',   emoji:'🐳'},
      {en:'Octopus',   he:'תמנון',     emoji:'🐙'},
      {en:'Crab',      he:'סרטן',      emoji:'🦀'},
      {en:'Jellyfish', he:'מדוזה',     emoji:'🪼'},
      {en:'Turtle',    he:'צב ים',     emoji:'🐢'},
      {en:'Seahorse',  he:'סוסון ים',  emoji:'🦄'},
      {en:'Starfish',  he:'כוכב ים',   emoji:'⭐'},
    ]
  },
  {
    id: 'farm',
    title: 'חיות חווה',
    emoji: '🐄',
    color: '#558B2F',
    words: [
      {en:'Cow',      he:'פרה',     emoji:'🐮'},
      {en:'Pig',      he:'חזיר',    emoji:'🐷'},
      {en:'Sheep',    he:'כבשה',    emoji:'🐑'},
      {en:'Chicken',  he:'תרנגולת', emoji:'🐔'},
      {en:'Rooster',  he:'תרנגול',  emoji:'🐓'},
      {en:'Horse',    he:'סוס',     emoji:'🐴'},
      {en:'Goat',     he:'עז',      emoji:'🐐'},
      {en:'Duck',     he:'ברווז',   emoji:'🦆'},
      {en:'Turkey',   he:'הודו',    emoji:'🦃'},
      {en:'Donkey',   he:'חמור',    emoji:'🫏'},
    ]
  },
  {
    id: 'insects',
    title: 'חרקים',
    emoji: '🦋',
    color: '#827717',
    words: [
      {en:'Butterfly', he:'פרפר',   emoji:'🦋'},
      {en:'Bee',       he:'דבורה',  emoji:'🐝'},
      {en:'Ant',       he:'נמלה',   emoji:'🐜'},
      {en:'Ladybug',   he:'פרת משה רבנו', emoji:'🐞'},
      {en:'Grasshopper',he:'חגב',   emoji:'🦗'},
      {en:'Spider',    he:'עכביש',  emoji:'🕷️'},
      {en:'Snail',     he:'חילזון', emoji:'🐌'},
      {en:'Worm',      he:'תולעת',  emoji:'🪱'},
      {en:'Mosquito',  he:'יתוש',   emoji:'🦟'},
      {en:'Dragonfly', he:'שפירית', emoji:'🪲'},
    ]
  },
  {
    id: 'jobs',
    title: 'מקצועות',
    emoji: '👩‍⚕️',
    color: '#00838F',
    words: [
      {en:'Doctor',    he:'רופא',    emoji:'👨‍⚕️'},
      {en:'Teacher',   he:'מורה',    emoji:'👩‍🏫'},
      {en:'Firefighter',he:'כבאי',   emoji:'👨‍🚒'},
      {en:'Police',    he:'שוטר',    emoji:'👮'},
      {en:'Chef',      he:'שף',      emoji:'👨‍🍳'},
      {en:'Farmer',    he:'חקלאי',   emoji:'👨‍🌾'},
      {en:'Pilot',     he:'טייס',    emoji:'👨‍✈️'},
      {en:'Astronaut', he:'אסטרונאוט',emoji:'👨‍🚀'},
      {en:'Dentist',   he:'רופא שיניים',emoji:'🦷'},
      {en:'Painter',   he:'צייר',    emoji:'🎨'},
    ]
  },
  {
    id: 'instruments',
    title: 'כלי נגינה',
    emoji: '🎵',
    color: '#AD1457',
    words: [
      {en:'Piano',     he:'פסנתר',  emoji:'🎹'},
      {en:'Guitar',    he:'גיטרה',  emoji:'🎸'},
      {en:'Drum',      he:'תוף',    emoji:'🥁'},
      {en:'Violin',    he:'כינור',  emoji:'🎻'},
      {en:'Trumpet',   he:'חצוצרה', emoji:'🎺'},
      {en:'Flute',     he:'חליל',   emoji:'🪈'},
      {en:'Harp',      he:'נבל',    emoji:'🎵'},
      {en:'Saxophone', he:'סקסופון',emoji:'🎷'},
      {en:'Microphone',he:'מיקרופון',emoji:'🎤'},
      {en:'Keyboard',  he:'קלידים', emoji:'🎹'},
    ]
  },
  {
    id: 'city',
    title: 'מקומות בעיר',
    emoji: '🏙️',
    color: '#37474F',
    words: [
      {en:'School',    he:'בית ספר',  emoji:'🏫'},
      {en:'Hospital',  he:'בית חולים',emoji:'🏥'},
      {en:'Park',      he:'פארק',     emoji:'🌳'},
      {en:'Library',   he:'ספרייה',   emoji:'📚'},
      {en:'Market',    he:'שוק',      emoji:'🛒'},
      {en:'Restaurant',he:'מסעדה',    emoji:'🍽️'},
      {en:'Bank',      he:'בנק',      emoji:'🏦'},
      {en:'Airport',   he:'שדה תעופה',emoji:'✈️'},
      {en:'Beach',     he:'חוף ים',   emoji:'🏖️'},
      {en:'Zoo',       he:'גן חיות',  emoji:'🦁'},
    ]
  },
  {
    id: 'space',
    title: 'חלל',
    emoji: '🚀',
    color: '#1A237E',
    words: [
      {en:'Sun',       he:'שמש',      emoji:'☀️'},
      {en:'Moon',      he:'ירח',       emoji:'🌙'},
      {en:'Star',      he:'כוכב',     emoji:'⭐'},
      {en:'Planet',    he:'כוכב לכת', emoji:'🪐'},
      {en:'Rocket',    he:'חללית',    emoji:'🚀'},
      {en:'Astronaut', he:'אסטרונאוט',emoji:'👨‍🚀'},
      {en:'Galaxy',    he:'גלקסיה',   emoji:'🌌'},
      {en:'Comet',     he:'שביט',     emoji:'☄️'},
      {en:'Satellite', he:'לוויין',   emoji:'🛸'},
      {en:'Black hole',he:'חור שחור', emoji:'🕳️'},
    ]
  },
  {
    id: 'playground',
    title: 'גן שעשועים',
    emoji: '🛝',
    color: '#F57F17',
    words: [
      {en:'Slide',      he:'מגלשה',    emoji:'🛝'},
      {en:'Swing',      he:'נדנדה',    emoji:'⛓️'},
      {en:'Sandbox',    he:'ארגז חול', emoji:'🏖️'},
      {en:'Seesaw',     he:'נדנדת גשר',emoji:'⚖️'},
      {en:'Monkey bars',he:'מסילות',   emoji:'🏋️'},
      {en:'Jump rope',  he:'חבל קפיצה',emoji:'🪢'},
      {en:'Trampoline', he:'טרמפולינה',emoji:'🤸'},
      {en:'Hula hoop',  he:'חישוק',    emoji:'⭕'},
      {en:'Frisbee',    he:'פריסבי',   emoji:'🥏'},
      {en:'Hide and seek',he:'מחבואים',emoji:'🙈'},
    ]
  },
  {
    id: 'house_items',
    title: 'חפצי בית',
    emoji: '🛋️',
    color: '#5D4037',
    words: [
      {en:'Sofa',       he:'ספה',        emoji:'🛋️'},
      {en:'Lamp',       he:'מנורה',      emoji:'💡'},
      {en:'Clock',      he:'שעון',       emoji:'🕐'},
      {en:'Mirror',     he:'מראה',       emoji:'🪞'},
      {en:'Fridge',     he:'מקרר',       emoji:'🧊'},
      {en:'Oven',       he:'תנור',       emoji:'🫙'},
      {en:'Washing machine',he:'מכונת כביסה',emoji:'🫧'},
      {en:'Television', he:'טלוויזיה',   emoji:'📺'},
      {en:'Phone',      he:'טלפון',      emoji:'📱'},
      {en:'Computer',   he:'מחשב',       emoji:'💻'},
    ]
  },
  {
    id: 'birds',
    title: 'ציפורים',
    emoji: '🐦',
    color: '#00ACC1',
    words: [
      {en:'Eagle',     he:'נשר',      emoji:'🦅'},
      {en:'Owl',       he:'ינשוף',    emoji:'🦉'},
      {en:'Parrot',    he:'תוכי',     emoji:'🦜'},
      {en:'Penguin',   he:'פינגווין', emoji:'🐧'},
      {en:'Flamingo',  he:'פלמינגו',  emoji:'🦩'},
      {en:'Peacock',   he:'טווס',     emoji:'🦚'},
      {en:'Duck',      he:'ברווז',    emoji:'🦆'},
      {en:'Hen',       he:'תרנגולת',  emoji:'🐔'},
      {en:'Pigeon',    he:'יונה',     emoji:'🕊️'},
      {en:'Swan',      he:'ברבור',    emoji:'🦢'},
    ]
  },
];

// ─────────────────────────────────────────
//  ביטויים יומיומיים — לפי קטגוריות
// ─────────────────────────────────────────
const phraseCategories = [
  {
    id: 'meeting',
    label: '🤝 נפגשים',
    color: '#7C4DFF',
    phrases: [
      {en:'Hello!',                   he:'!שלום',                   emoji:'👋'},
      {en:'Hi!',                      he:'!היי',                    emoji:'😊'},
      {en:'Good morning!',            he:'!בוקר טוב',               emoji:'🌅'},
      {en:'Good afternoon!',          he:'!צהריים טובים',            emoji:'☀️'},
      {en:'Good evening!',            he:'!ערב טוב',                emoji:'🌆'},
      {en:'Good night!',              he:'!לילה טוב',               emoji:'🌙'},
      {en:'Goodbye!',                 he:'!להתראות',                emoji:'🙋'},
      {en:'Bye bye!',                 he:'!ביי ביי',                emoji:'👋'},
      {en:'See you later!',           he:'!נתראה אחר כך',            emoji:'🕐'},
      {en:'See you tomorrow!',        he:'!נתראה מחר',              emoji:'📅'},
      {en:'Have a great day!',        he:'!יום נהדר',               emoji:'🌞'},
      {en:"What's your name?",        he:'?מה שמך',                emoji:'🏷️'},
      {en:'My name is...',            he:'שמי...',                  emoji:'😎'},
      {en:'Nice to meet you!',        he:'!נעים להכיר',             emoji:'🤝'},
      {en:'How are you?',             he:'?מה שלומך',              emoji:'💬'},
      {en:"I'm fine, thanks!",        he:'!אני בסדר, תודה',         emoji:'😄'},
      {en:"I'm great!",               he:'!אני מצוין/ת',            emoji:'🤩'},
      {en:'How old are you?',         he:'?בן/בת כמה אתה/את',      emoji:'🎂'},
      {en:'I am ... years old.',      he:'אני בן/בת ... שנים',     emoji:'🔢'},
      {en:'Where are you from?',      he:'?מאיפה אתה/את',          emoji:'🌍'},
      {en:'I am from Israel.',        he:'אני מישראל',             emoji:'🇮🇱'},
      {en:'Do you speak English?',    he:'?אתה/את מדבר/ת אנגלית',  emoji:'🗣️'},
      {en:'A little bit.',            he:'קצת',                     emoji:'🤏'},
    ]
  },
  {
    id: 'polite',
    label: '🙏 נימוס',
    color: '#E91E63',
    phrases: [
      {en:'Please',                   he:'בבקשה',                  emoji:'🙏'},
      {en:'Thank you!',               he:'!תודה',                  emoji:'💛'},
      {en:'Thank you very much!',     he:'!תודה רבה',              emoji:'🙏'},
      {en:"You're welcome!",          he:'!אין בעד מה',            emoji:'😊'},
      {en:'Sorry!',                   he:'!סליחה',                 emoji:'😅'},
      {en:'Excuse me.',               he:'.סליחה',                 emoji:'🤝'},
      {en:'No problem!',              he:'!אין בעיה',              emoji:'😎'},
      {en:'Of course!',               he:'!כמובן',                 emoji:'✅'},
      {en:'Yes',                      he:'כן',                     emoji:'✅'},
      {en:'No',                       he:'לא',                     emoji:'❌'},
      {en:'Maybe',                    he:'אולי',                   emoji:'🤔'},
      {en:'That is very kind!',       he:'!זה מאוד נחמד',          emoji:'💗'},
      {en:'After you!',               he:'!אחרייך/ך',              emoji:'🚪'},
      {en:"I'm sorry to hear that.",  he:'.מצטער/ת לשמוע',        emoji:'🥺'},
      {en:'Can you help me?',         he:'?אתה/את יכול/ה לעזור לי',emoji:'🆘'},
      {en:"I don't understand.",      he:'.אני לא מבין/ה',         emoji:'😕'},
      {en:'Can you repeat, please?',  he:'?אפשר לחזור, בבקשה',    emoji:'🔁'},
      {en:'Can you speak slower?',    he:'?אפשר לדבר יותר לאט',   emoji:'🐢'},
      {en:"I don't know.",            he:'.אני לא יודע/ת',         emoji:'🤷'},
    ]
  },
  {
    id: 'school',
    label: '🏫 בבית ספר',
    color: '#1565C0',
    phrases: [
      {en:'I have a question.',       he:'יש לי שאלה',             emoji:'🙋'},
      {en:"I don't know the answer.", he:'אני לא יודע/ת את התשובה',emoji:'🤷'},
      {en:"I'm done!",                he:'!סיימתי',                emoji:'🎉'},
      {en:'Can I go to the bathroom?',he:'?אפשר לצאת לשירותים',   emoji:'🚻'},
      {en:"I don't have a pencil.",   he:'אין לי עיפרון',          emoji:'✏️'},
      {en:'Can I borrow a pen?',      he:'?אפשר ללוות עט',         emoji:'🖊️'},
      {en:'Where is my bag?',         he:'?איפה התיק שלי',         emoji:'🎒'},
      {en:'I forgot my homework.',    he:'שכחתי את שיעורי הבית',   emoji:'📓'},
      {en:'Can you explain again?',   he:'?אפשר להסביר שוב',       emoji:'🔄'},
      {en:'I understand!',            he:'!אני מבין/ה',            emoji:'💡'},
      {en:"Let's go!",                he:'!יאללה',                 emoji:'🚀'},
      {en:'Wait for me!',             he:'!חכה/י לי',              emoji:'⏳'},
      {en:"It's my turn!",            he:'!זה התור שלי',           emoji:'👆'},
      {en:'Can we play outside?',     he:'?אפשר לשחק בחוץ',       emoji:'⛹️'},
      {en:'I need help.',             he:'אני צריך/ה עזרה',        emoji:'🆘'},
      {en:'This is too hard.',        he:'זה קשה מדי',             emoji:'😓'},
      {en:'This is easy!',            he:'!זה קל',                 emoji:'😎'},
      {en:'Can I work with a friend?',he:'?אפשר לעבוד עם חבר/ה',  emoji:'👯'},
    ]
  },
  {
    id: 'home',
    label: '🏠 בבית',
    color: '#FF8F00',
    phrases: [
      {en:"I'm home!",                he:'!הגעתי הביתה',           emoji:'🏠'},
      {en:"I'm hungry!",              he:'!אני רעב/ה',             emoji:'🍽️'},
      {en:"I'm thirsty!",             he:'!אני צמא/ה',             emoji:'💧'},
      {en:'Can I have a snack?',      he:'?אפשר חטיף',             emoji:'🍎'},
      {en:"I'm tired.",               he:'.אני עייף/ה',            emoji:'😴'},
      {en:'I want to watch TV.',      he:'.אני רוצה לראות טלוויזיה',emoji:'📺'},
      {en:'Can I play outside?',      he:'?אפשר לשחק בחוץ',       emoji:'🌳'},
      {en:'I brushed my teeth.',      he:'צחצחתי שיניים',          emoji:'🦷'},
      {en:'I washed my hands.',       he:'שטפתי ידיים',            emoji:'🧼'},
      {en:"It's time for bed.",       he:'הגיע זמן לישון',         emoji:'🛏️'},
      {en:'Can you read me a story?', he:'?אפשר לקרוא לי סיפור',  emoji:'📖'},
      {en:'I love you, Mom!',         he:'!אני אוהב/ת אותך, אמא', emoji:'❤️'},
      {en:'I love you, Dad!',         he:'!אני אוהב/ת אותך, אבא', emoji:'💙'},
      {en:'Where is my toy?',         he:'?איפה הצעצוע שלי',      emoji:'🧸'},
      {en:"I'm ready!",               he:'!אני מוכן/ה',            emoji:'💪'},
      {en:"Let's eat!",               he:'!בוא/י נאכל',            emoji:'🍽️'},
      {en:'It smells delicious!',     he:'!זה מריח טעים',         emoji:'😋'},
      {en:'Can I have more?',         he:'?אפשר עוד קצת',          emoji:'🍪'},
    ]
  },
  {
    id: 'restaurant',
    label: '🍽️ במסעדה',
    color: '#E64A19',
    phrases: [
      {en:'A table for two, please.',  he:'.שולחן לשניים, בבקשה',  emoji:'🪑'},
      {en:'Can I see the menu?',       he:'?אפשר לראות את התפריט',emoji:'📋'},
      {en:'I would like pizza, please.',he:'.אני רוצה פיצה, בבקשה',emoji:'🍕'},
      {en:'What do you recommend?',    he:'?מה אתה/את ממליץ/ה',   emoji:'⭐'},
      {en:'I am allergic to...',       he:'אני אלרגי/ת ל...',     emoji:'⚠️'},
      {en:'No onions, please.',        he:'.בלי בצל, בבקשה',      emoji:'🧅'},
      {en:'Can I have water, please?', he:'?אפשר מים, בבקשה',     emoji:'💧'},
      {en:'It is delicious!',          he:'!זה טעים מאוד',         emoji:'😋'},
      {en:'The bill, please.',         he:'.חשבון, בבקשה',        emoji:'🧾'},
      {en:'Can we take this home?',    he:'?אפשר לקחת את זה הביתה',emoji:'📦'},
      {en:"I'm full!",                 he:'!אני שבע/ה',            emoji:'😌'},
      {en:'This is very good!',        he:'!זה מאוד טוב',          emoji:'👍'},
      {en:'Can I have a fork?',        he:'?אפשר מזלג',           emoji:'🍴'},
      {en:'More juice, please.',       he:'.עוד מיץ, בבקשה',      emoji:'🥤'},
    ]
  },
  {
    id: 'store',
    label: '🛒 בחנות',
    color: '#00897B',
    phrases: [
      {en:'How much does this cost?',  he:'?כמה זה עולה',          emoji:'💰'},
      {en:'That is too expensive.',    he:'.זה יקר מדי',           emoji:'😬'},
      {en:'Do you have this in red?',  he:'?יש את זה בצבע אדום',  emoji:'🔴'},
      {en:'I would like to buy this.', he:'.אני רוצה לקנות את זה',emoji:'🛍️'},
      {en:'Can I try this on?',        he:'?אפשר למדוד את זה',    emoji:'👕'},
      {en:'Where is the checkout?',    he:'?איפה הקופה',           emoji:'🏧'},
      {en:'Can I pay by card?',        he:'?אפשר לשלם בכרטיס',    emoji:'💳'},
      {en:'Do you have a bag?',        he:'?יש לכם שקית',          emoji:'🛍️'},
      {en:'I am just looking.',        he:'אני רק מסתכל/ת',        emoji:'👀'},
      {en:"I'd like a refund.",        he:'.אני רוצה החזר כסף',   emoji:'💵'},
      {en:'Where can I find milk?',    he:'?איפה אפשר למצוא חלב', emoji:'🥛'},
      {en:'This is on sale!',          he:'!זה במבצע',             emoji:'🏷️'},
    ]
  },
  {
    id: 'playground',
    label: '🛝 במגרש המשחקים',
    color: '#43A047',
    phrases: [
      {en:'Do you want to play?',      he:'?אתה/את רוצה לשחק',    emoji:'🎮'},
      {en:"Let's play together!",      he:'!בוא/י נשחק ביחד',     emoji:'🤝'},
      {en:'It is my turn!',            he:'!זה התור שלי',         emoji:'☝️'},
      {en:"It's your turn!",           he:'!זה התור שלך',         emoji:'👉'},
      {en:'That is not fair!',         he:'!זה לא הוגן',          emoji:'😤'},
      {en:"Let's be friends!",         he:'!בוא/י נהיה חברים',    emoji:'🤝'},
      {en:'Can I join?',               he:'?אפשר להצטרף',        emoji:'🙋'},
      {en:'Push me on the swing!',     he:'!תדחוף/י אותי בנדנדה', emoji:'🪁'},
      {en:'Race you to the tree!',     he:'!תחרות עד העץ',        emoji:'🏃'},
      {en:"You're it!",                he:'!אתה/את "זה"',         emoji:'👆'},
      {en:'Be careful!',               he:'!תהיה/י זהיר/ה',       emoji:'⚠️'},
      {en:'That was fun!',             he:'!זה היה כיף',          emoji:'🎉'},
    ]
  },
  {
    id: 'feelings_ph',
    label: '😊 רגשות',
    color: '#FFB300',
    phrases: [
      {en:"I'm happy!",               he:'!אני שמח/ה',            emoji:'😄'},
      {en:"I'm sad.",                 he:'.אני עצוב/ה',           emoji:'😢'},
      {en:"I'm angry!",               he:'!אני כועס/ת',           emoji:'😡'},
      {en:"I'm scared.",              he:'.אני מפחד/ת',           emoji:'😱'},
      {en:"I'm excited!",             he:'!אני נרגש/ת',           emoji:'🤩'},
      {en:"I'm bored.",               he:'.אני משועמם/ת',         emoji:'😑'},
      {en:"I'm proud!",               he:'!אני גאה',              emoji:'😤'},
      {en:"I'm surprised!",           he:'!אני מופתע/ת',          emoji:'😲'},
      {en:'I feel sick.',             he:'אני מרגיש/ה לא טוב',    emoji:'🤒'},
      {en:'I love you!',              he:'!אני אוהב/ת אותך',      emoji:'❤️'},
      {en:"That's amazing!",          he:'!זה מדהים',             emoji:'🌟'},
      {en:"That's funny!",            he:'!זה מצחיק',             emoji:'😂'},
      {en:'I miss you!',              he:'!אני מתגעגע/ת אליך',   emoji:'🥺'},
      {en:"I'm nervous.",             he:'.אני לחוץ/ה',           emoji:'😰'},
      {en:'This is so cool!',         he:'!זה כל כך מגניב',       emoji:'😎'},
    ]
  },
  {
    id: 'celebrate',
    label: '🎉 חגיגות',
    color: '#AD1457',
    phrases: [
      {en:'Happy Birthday!',          he:'!יום הולדת שמח',        emoji:'🎂'},
      {en:'Happy New Year!',          he:'!שנה טובה',             emoji:'🎆'},
      {en:'Congratulations!',         he:'!מזל טוב',              emoji:'🎊'},
      {en:'Good luck!',               he:'!בהצלחה',               emoji:'🍀'},
      {en:'Well done!',               he:'!כל הכבוד',             emoji:'🏆'},
      {en:'Good job!',                he:'!עשית עבודה טובה',      emoji:'👏'},
      {en:"You're amazing!",          he:'!אתה/את מדהים/ה',       emoji:'🌟'},
      {en:'I am so proud of you!',    he:'!אני כל כך גאה בך',    emoji:'🥲'},
      {en:'You can do it!',           he:'!אתה/את יכול/ה!',       emoji:'💪'},
      {en:'That is wonderful!',       he:'!זה נפלא',              emoji:'🌈'},
      {en:'Cheers!',                  he:'!לחיים',                emoji:'🥂'},
      {en:'Have fun!',                he:'!תהיה/י בכיף',          emoji:'🎈'},
    ]
  },
];

// ─────────────────────────────────────────
//  משפטים בסיסיים (I am / I like / I want / I have / I can)
// ─────────────────────────────────────────
const sentenceGroups = [
  {
    id: 'iam',
    label: '🙋 I am',
    color: '#AB47BC',
    info: '"I am" = "אני" — לתאר את עצמך!',
    sentences: [
      {en:'I am happy!',            he:'!אני שמח/ה',               emoji:'😄', tip:'כשמרגישים טוב'},
      {en:'I am sad.',              he:'.אני עצוב/ה',              emoji:'😢', tip:'כשמרגישים עצוב'},
      {en:'I am hungry!',           he:'!אני רעב/ה',               emoji:'🍽️', tip:'כשרוצים לאכול'},
      {en:'I am thirsty!',          he:'!אני צמא/ה',               emoji:'💧', tip:'כשרוצים לשתות'},
      {en:'I am tired.',            he:'.אני עייף/ה',              emoji:'😴', tip:'כשרוצים לישון'},
      {en:'I am bored.',            he:'.אני משועמם/ת',            emoji:'😑', tip:'כשאין מה לעשות'},
      {en:'I am excited!',          he:'!אני נרגש/ת',              emoji:'🤩', tip:'כשמחכים למשהו'},
      {en:'I am angry.',            he:'.אני כועס/ת',              emoji:'😡', tip:'כשמשהו מרגיז'},
      {en:'I am scared.',           he:'.אני מפחד/ת',              emoji:'😱', tip:'כשמרגישים פחד'},
      {en:'I am proud!',            he:'!אני גאה',                 emoji:'😤', tip:'כשמצליחים במשהו'},
      {en:'I am ready!',            he:'!אני מוכן/ה',              emoji:'💪', tip:'כשמוכנים להתחיל'},
      {en:'I am sick.',             he:'.אני חולה',                emoji:'🤒', tip:'כשלא מרגישים טוב'},
      {en:'I am cold.',             he:'.קר לי',                   emoji:'🥶', tip:'כשקר בחוץ'},
      {en:'I am hot.',              he:'.חם לי',                   emoji:'🥵', tip:'כשחם בחוץ'},
      {en:'I am a boy.',            he:'.אני ילד',                 emoji:'👦', tip:'ספר/י על עצמך'},
      {en:'I am a girl.',           he:'.אני ילדה',                emoji:'👧', tip:'ספר/י על עצמך'},
      {en:'I am six years old.',    he:'.אני בן/בת שש',            emoji:'🎂', tip:'החלף/י את המספר לגיל שלך!'},
      {en:'I am at school.',        he:'.אני בבית ספר',            emoji:'🏫', tip:'להגיד איפה אתה/את'},
      {en:'I am at home.',          he:'.אני בבית',                emoji:'🏠', tip:'להגיד איפה אתה/את'},
    ]
  },
  {
    id: 'ilike',
    label: '❤️ I like',
    color: '#E91E63',
    info: '"I like" = "אני אוהב/ת" — ספר/י מה אוהבים!',
    sentences: [
      {en:'I like cats!',           he:'!אני אוהב/ת חתולים',       emoji:'🐱', tip:'החלף/י "cats" בחיה שאוהבים'},
      {en:'I like dogs!',           he:'!אני אוהב/ת כלבים',        emoji:'🐶', tip:'חיות מחמד'},
      {en:'I like pizza!',          he:'!אני אוהב/ת פיצה',         emoji:'🍕', tip:'האוכל האהוב'},
      {en:'I like ice cream!',      he:'!אני אוהב/ת גלידה',        emoji:'🍦', tip:'קינוח מתוק!'},
      {en:'I like soccer!',         he:'!אני אוהב/ת כדורגל',       emoji:'⚽', tip:'ספורט'},
      {en:'I like swimming!',       he:'!אני אוהב/ת לשחות',        emoji:'🏊', tip:'ספורט מים'},
      {en:'I like to read.',        he:'.אני אוהב/ת לקרוא',        emoji:'📖', tip:'פעולות שנהנים'},
      {en:'I like to draw.',        he:'.אני אוהב/ת לצייר',        emoji:'🎨', tip:'אומנות'},
      {en:'I like to dance!',       he:'!אני אוהב/ת לרקוד',        emoji:'💃', tip:'מוזיקה ותנועה'},
      {en:'I like music!',          he:'!אני אוהב/ת מוזיקה',       emoji:'🎵', tip:'תחביב'},
      {en:'I like playing games!',  he:'!אני אוהב/ת לשחק משחקים',  emoji:'🎮', tip:'משחקים'},
      {en:'I like chocolate!',      he:'!אני אוהב/ת שוקולד',       emoji:'🍫', tip:'ממתקים!'},
      {en:'I like the park!',       he:'!אני אוהב/ת את הפארק',     emoji:'🌳', tip:'מקומות שאוהבים'},
      {en:'I like my family!',      he:'!אני אוהב/ת את המשפחה',    emoji:'👨‍👩‍👧', tip:'הדבר הכי חשוב!'},
      {en:'I like summer!',         he:'!אני אוהב/ת קיץ',          emoji:'☀️', tip:'עונות השנה'},
      {en:'I like the beach!',      he:'!אני אוהב/ת את הים',       emoji:'🏖️', tip:'מקומות שאוהבים'},
    ]
  },
  {
    id: 'iwant',
    label: '🌟 I want',
    color: '#FF8F00',
    info: '"I want" = "אני רוצה" — תמיד להוסיף "please"!',
    sentences: [
      {en:'I want water, please.',  he:'.אני רוצה מים, בבקשה',     emoji:'💧', tip:'תמיד "please" — זה מנומס!'},
      {en:'I want to play!',        he:'!אני רוצה לשחק',           emoji:'🎮', tip:'להגיד מה רוצים לעשות'},
      {en:'I want to eat.',         he:'.אני רוצה לאכול',          emoji:'🍽️', tip:'כשרעבים'},
      {en:'I want more, please.',   he:'.אני רוצה עוד, בבקשה',     emoji:'🍪', tip:'לבקש עוד'},
      {en:'I want a hug!',          he:'!אני רוצה חיבוק',          emoji:'🤗', tip:'מאוד חשוב לדעת!'},
      {en:'I want to sleep.',       he:'.אני רוצה לישון',          emoji:'😴', tip:'כשמאוד עייפים'},
      {en:'I want to go home.',     he:'.אני רוצה לחזור הביתה',    emoji:'🏠', tip:'כשמתגעגעים'},
      {en:'I want to go outside.',  he:'.אני רוצה לצאת החוצה',     emoji:'🌞', tip:'לבקש לצאת לחצר'},
      {en:'I want to watch TV.',    he:'.אני רוצה לראות טלוויזיה', emoji:'📺', tip:'פעילות בבית'},
      {en:'I want a cookie.',       he:'.אני רוצה עוגייה',         emoji:'🍪', tip:'לבקש ממתק'},
      {en:'I want to draw.',        he:'.אני רוצה לצייר',          emoji:'🎨', tip:'פעילות יצירה'},
      {en:'I want to read a book.', he:'.אני רוצה לקרוא ספר',      emoji:'📚', tip:'לקריאה'},
      {en:'I want to ride my bike.',he:'.אני רוצה לרכוב על אופניים',emoji:'🚲', tip:'פעילות בחוץ'},
    ]
  },
  {
    id: 'ihave',
    label: '📦 I have',
    color: '#26C6DA',
    info: '"I have" = "יש לי" — ספר/י מה יש לך!',
    sentences: [
      {en:'I have a dog.',          he:'.יש לי כלב',               emoji:'🐶', tip:'החלף/י "dog" בחיה שלך'},
      {en:'I have a cat.',          he:'.יש לי חתול',              emoji:'🐱', tip:'חיות מחמד'},
      {en:'I have a brother.',      he:'.יש לי אח',                emoji:'👦', tip:'ספר/י על המשפחה'},
      {en:'I have a sister.',       he:'.יש לי אחות',              emoji:'👧', tip:'ספר/י על המשפחה'},
      {en:'I have a new pencil!',   he:'!יש לי עיפרון חדש',        emoji:'✏️', tip:'אפשר להחליף "pencil" בכל חפץ'},
      {en:'I have a question.',     he:'.יש לי שאלה',              emoji:'🙋', tip:'בכיתה'},
      {en:'I have an idea!',        he:'!יש לי רעיון',             emoji:'💡', tip:'כשחושבים על רעיון'},
      {en:'I have blue eyes.',      he:'.יש לי עיניים כחולות',     emoji:'👁️', tip:'צבע + חלק גוף'},
      {en:'I have brown hair.',     he:'.יש לי שיער חום',          emoji:'💇', tip:'לתאר מראה חיצוני'},
      {en:'I have a big family.',   he:'.יש לי משפחה גדולה',       emoji:'👨‍👩‍👧‍👦', tip:'לתאר את המשפחה'},
      {en:'I have a red ball.',     he:'.יש לי כדור אדום',         emoji:'🔴', tip:'צבע + עצם'},
      {en:'I have a lot of toys.',  he:'.יש לי הרבה צעצועים',      emoji:'🧸', tip:'כמות'},
    ]
  },
  {
    id: 'ican',
    label: '💪 I can',
    color: '#66BB6A',
    info: '"I can" = "אני יכול/ה" — ספר/י מה אתה/את יכול/ה לעשות!',
    sentences: [
      {en:'I can run!',             he:'!אני יכול/ה לרוץ',         emoji:'🏃', tip:'ספורט ותנועה'},
      {en:'I can swim.',            he:'.אני יכול/ה לשחות',        emoji:'🏊', tip:'בבריכה'},
      {en:'I can jump!',            he:'!אני יכול/ה לקפוץ',        emoji:'🦘', tip:'קפיצה'},
      {en:'I can read.',            he:'.אני יכול/ה לקרוא',        emoji:'📖', tip:'קריאה'},
      {en:'I can write.',           he:'.אני יכול/ה לכתוב',        emoji:'✍️', tip:'כתיבה'},
      {en:'I can draw!',            he:'!אני יכול/ה לצייר',        emoji:'🎨', tip:'אמנות'},
      {en:'I can sing!',            he:'!אני יכול/ה לשיר',         emoji:'🎤', tip:'מוזיקה'},
      {en:'I can dance!',           he:'!אני יכול/ה לרקוד',        emoji:'💃', tip:'ריקוד'},
      {en:'I can cook!',            he:'!אני יכול/ה לבשל',         emoji:'🍳', tip:'בישול'},
      {en:'I can help!',            he:'!אני יכול/ה לעזור',        emoji:'🙌', tip:'להציע עזרה'},
      {en:'I can count to ten.',    he:'.אני יכול/ה לספור עד עשר', emoji:'🔢', tip:'ספירה'},
      {en:"I can't do it.",         he:'.אני לא יכול/ה',           emoji:'😟', tip:'כשמשהו קשה מדי'},
      {en:'I can try!',             he:'!אני יכול/ה לנסות',        emoji:'💪', tip:'גישה חיובית!'},
      {en:'I can do it!',           he:'!אני יכול/ה!',             emoji:'🌟', tip:'ביטחון עצמי!'},
    ]
  },
  {
    id: 'igo',
    label: '🚶 I go',
    color: '#FF5722',
    info: '"I go" = "אני הולך/ת" — לספר לאן הולכים!',
    sentences: [
      {en:'I go to school.',        he:'.אני הולך/ת לבית ספר',     emoji:'🏫', tip:'כל יום בבוקר'},
      {en:'I go home.',             he:'.אני הולך/ת הביתה',        emoji:'🏠', tip:'בסוף היום'},
      {en:'I go to the park.',      he:'.אני הולך/ת לפארק',        emoji:'🌳', tip:'אחר הצהריים'},
      {en:'I go to the beach!',     he:'!אני הולך/ת לים',          emoji:'🏖️', tip:'בקיץ'},
      {en:'I go by bus.',           he:'.אני נוסע/ת באוטובוס',     emoji:'🚌', tip:'תחבורה'},
      {en:'I go by car.',           he:'.אני נוסע/ת במכונית',      emoji:'🚗', tip:'תחבורה'},
      {en:'I go on foot.',          he:'.אני הולך/ת ברגל',         emoji:'👟', tip:'ללא תחבורה'},
      {en:'I go to sleep early.',   he:'.אני הולך/ת לישון מוקדם',  emoji:'😴', tip:'שגרת לילה'},
    ]
  },
  {
    id: 'isee',
    label: '👀 I see',
    color: '#00897B',
    info: '"I see" = "אני רואה" — לתאר מה רואים!',
    sentences: [
      {en:'I see a dog.',           he:'.אני רואה כלב',            emoji:'🐶', tip:'לתאר מה יש סביב'},
      {en:'I see a big tree.',      he:'.אני רואה עץ גדול',        emoji:'🌳', tip:'גודל + עצם'},
      {en:'I see a red car.',       he:'.אני רואה מכונית אדומה',   emoji:'🚗', tip:'צבע + עצם'},
      {en:'I see the sun!',         he:'!אני רואה את השמש',        emoji:'☀️', tip:'מזג אוויר'},
      {en:'I see a butterfly!',     he:'!אני רואה פרפר',           emoji:'🦋', tip:'טבע'},
      {en:'I see my friend.',       he:'.אני רואה את החבר/ה שלי',  emoji:'🤝', tip:'אנשים'},
      {en:'I see a rainbow!',       he:'!אני רואה קשת',            emoji:'🌈', tip:'מזג אוויר'},
      {en:'I see stars!',           he:'!אני רואה כוכבים',         emoji:'⭐', tip:'בלילה'},
    ]
  },
];

// grammarLessons defined below (comprehensive version)

// ─────────────────────────────────────────
//  שירים וחרוזים
// ─────────────────────────────────────────
const songs = [
  {
    id: 'abc_song',
    title: 'שיר האלפבית',
    emoji: '🎵',
    color: '#4FC3F7',
    lines: [
      {text:'A B C D E F G', he:''},
      {text:'H I J K L M N O P', he:''},
      {text:'Q R S', he:''},
      {text:'T U V', he:''},
      {text:'W X Y and Z', he:''},
      {text:'Now I know my ABCs,', he:'עכשיו אני יודע/ת את האלפבית שלי'},
      {text:'Next time won\'t you sing with me?', he:'?בפעם הבאה תשיר/י איתי'},
    ]
  },
  {
    id: 'head_shoulders',
    title: 'Head, Shoulders',
    emoji: '🙋',
    color: '#66BB6A',
    lines: [
      {text:'Head, shoulders, knees and toes,', he:'ראש, כתפיים, ברכיים ואצבעות'},
      {text:'Knees and toes!', he:'ברכיים ואצבעות!'},
      {text:'Head, shoulders, knees and toes,', he:'ראש, כתפיים, ברכיים ואצבעות'},
      {text:'Knees and toes!', he:'ברכיים ואצבעות!'},
      {text:'Eyes and ears and mouth and nose,', he:'עיניים, אוזניים, פה ואף'},
      {text:'Head, shoulders, knees and toes,', he:'ראש, כתפיים, ברכיים ואצבעות'},
      {text:'Knees and toes!', he:'ברכיים ואצבעות!'},
    ]
  },
  {
    id: 'old_mcdonald',
    title: 'Old MacDonald',
    emoji: '🚜',
    color: '#FFA726',
    lines: [
      {text:'Old MacDonald had a farm,', he:'למקדונלד הזקן הייתה חווה'},
      {text:'E-I-E-I-O!', he:''},
      {text:'And on his farm he had a cow,', he:'ובחווה שלו הייתה פרה'},
      {text:'E-I-E-I-O!', he:''},
      {text:'With a moo moo here,', he:'עם מו מו כאן'},
      {text:'And a moo moo there,', he:'ומו מו שם'},
      {text:'Here a moo, there a moo,', he:'כאן מו, שם מו'},
      {text:'Everywhere a moo moo!', he:'!בכל מקום מו מו'},
    ]
  },
  {
    id: 'twinkle',
    title: 'Twinkle Twinkle',
    emoji: '⭐',
    color: '#AB47BC',
    lines: [
      {text:'Twinkle, twinkle, little star,', he:'מנצנצת, מנצנצת, כוכב קטן'},
      {text:'How I wonder what you are!', he:'!כמה אני תוהה מה אתה'},
      {text:'Up above the world so high,', he:'גבוה מעל העולם'},
      {text:'Like a diamond in the sky.', he:'.כמו יהלום בשמיים'},
      {text:'Twinkle, twinkle, little star,', he:'מנצנצת, מנצנצת, כוכב קטן'},
      {text:'How I wonder what you are!', he:'!כמה אני תוהה מה אתה'},
    ]
  },
  {
    id: 'wheels_bus',
    title: 'Wheels on the Bus',
    emoji: '🚌',
    color: '#EF5350',
    lines: [
      {text:'The wheels on the bus go round and round,', he:'הגלגלים באוטובוס מסתובבים'},
      {text:'Round and round, round and round!', he:'מסתובבים, מסתובבים!'},
      {text:'The wheels on the bus go round and round,', he:'הגלגלים באוטובוס מסתובבים'},
      {text:'All through the town!', he:'!בכל העיר'},
      {text:'The horn on the bus goes beep beep beep...', he:'הצופר באוטובוס עושה בי בי בי'},
      {text:'The wipers on the bus go swish swish swish...', he:'המגבים באוטובוס עושים שואוש'},
    ]
  },
];

// ─────────────────────────────────────────
//  חידון מילים (pool)
// ─────────────────────────────────────────
const wordQuizPool = [
  {q:'מה זה? 🐱', opts:['Cat','Dog','Bird','Fish'],      ans:'Cat',       emoji:'🐱'},
  {q:'מה זה? ☀️', opts:['Moon','Rain','Sun','Star'],     ans:'Sun',       emoji:'☀️'},
  {q:'מה זה? 🍎', opts:['Banana','Apple','Mango','Pear'],ans:'Apple',     emoji:'🍎'},
  {q:'מה זה? 🔵', opts:['Red','Green','Blue','Yellow'],  ans:'Blue',      emoji:'🔵'},
  {q:'מה זה? 🐶', opts:['Cat','Fish','Dog','Rabbit'],    ans:'Dog',       emoji:'🐶'},
  {q:'מה זה? 3️⃣', opts:['Two','Four','Three','Five'],   ans:'Three',     emoji:'3️⃣'},
  {q:'מה זה? 🍕', opts:['Bread','Cake','Milk','Pizza'],  ans:'Pizza',     emoji:'🍕'},
  {q:'מה זה? 🦋', opts:['Bird','Butterfly','Bee','Fish'],ans:'Butterfly', emoji:'🦋'},
  {q:'מה זה? 🔴', opts:['Blue','Red','Green','Pink'],    ans:'Red',       emoji:'🔴'},
  {q:'מה זה? ✏️', opts:['Pen','Ruler','Pencil','Book'],  ans:'Pencil',    emoji:'✏️'},
  {q:'מה זה? 🐘', opts:['Horse','Lion','Cow','Elephant'],ans:'Elephant',  emoji:'🐘'},
  {q:'מה זה? 🛏️', opts:['Chair','Table','Bed','Door'],   ans:'Bed',       emoji:'🛏️'},
  {q:'מה זה? 🟢', opts:['Blue','Green','Yellow','Pink'], ans:'Green',     emoji:'🟢'},
  {q:'מה זה? 8️⃣', opts:['Six','Nine','Eight','Seven'],  ans:'Eight',     emoji:'8️⃣'},
  {q:'מה זה? 🥛', opts:['Water','Juice','Milk','Tea'],   ans:'Milk',      emoji:'🥛'},
  {q:'מה זה? 🐯', opts:['Lion','Cat','Tiger','Leopard'], ans:'Tiger',     emoji:'🐯'},
  {q:'מה זה? 🚗', opts:['Truck','Bus','Car','Van'],      ans:'Car',       emoji:'🚗'},
  {q:'מה זה? 👕', opts:['Dress','Socks','Shirt','Coat'], ans:'Shirt',     emoji:'👕'},
  {q:'מה זה? 🌸', opts:['Tree','Leaf','Grass','Flower'], ans:'Flower',    emoji:'🌸'},
  {q:'מה זה? 👨', opts:['Mom','Dad','Brother','Uncle'],  ans:'Dad',       emoji:'👨'},
];

// ─────────────────────────────────────────
//  חידון משפטים
// ─────────────────────────────────────────
const sentenceQuizData = [
  {q:'כשאתה/את שמח/ה:',         opts:['I am happy!','I want happy!','I like happy!','Happy I am!'], ans:'I am happy!',            emoji:'😄'},
  {q:'רוצים לבקש מים:',         opts:['I like water','I am water','I want water, please.','Water I want'], ans:'I want water, please.',emoji:'💧'},
  {q:'אוהב/ת חתולים:',          opts:['I am cats!','I want cats!','I like cats!','Cats I like!'],   ans:'I like cats!',           emoji:'🐱'},
  {q:'עייף/ה:',                 opts:['I am tired.','I like tired.','I want tired.','Tired I am.'], ans:'I am tired.',            emoji:'😴'},
  {q:'רוצים לשחק:',             opts:['I am to play!','I like to play!','I want to play!','Play I want!'],ans:'I want to play!',  emoji:'🎮'},
  {q:'אוהב/ת פיצה:',            opts:['I want pizza!','I am pizza!','I like pizza!','Pizza I like!'],ans:'I like pizza!',         emoji:'🍕'},
  {q:'רוצים חיבוק:',            opts:['I like a hug!','I want a hug!','I am a hug!','Hug I want!'],  ans:'I want a hug!',         emoji:'🤗'},
  {q:'יש לך שאלה:',             opts:['I want a question.','I have a question.','I am a question.','Question I have.'],ans:'I have a question.',emoji:'🙋'},
  {q:'אתה/את יכול/ה לשחות:',    opts:['I like to swim.','I am to swim.','I can swim.','Swim I can.'], ans:'I can swim.',           emoji:'🏊'},
  {q:'בן/בת שבע:',              opts:['I am seven years old.','I like seven.','I want seven.','Seven I am.'],ans:'I am seven years old.',emoji:'🎂'},
];

// ─────────────────────────────────────────
//  שיעורי דקדוק
//  כל שיעור: id, emoji, color, title, explanation[], quiz[]
//  explanation: { rule, example, he }
//  quiz: { emoji, q, opts[], ans }
// ─────────────────────────────────────────
const grammarLessons = [
  {
    id: 'to_be',
    emoji: '🔗',
    color: '#7C4DFF',
    title: '"to be" — להיות',
    explanation: [
      { rule: 'I am', example: 'I am happy.', he: 'אני שמח/ה.' },
      { rule: 'You are', example: 'You are kind.', he: 'אתה/את אדיב/ה.' },
      { rule: 'He / She / It is', example: 'She is tall. The cat is small.', he: 'הוא/היא/זה — משתמשים ב-is' },
      { rule: 'We / You / They are', example: 'We are friends. They are at school.', he: 'אנחנו/הם/אתם — משתמשים ב-are' },
      { rule: "קיצורים: I'm, You're, He's, She's, It's, We're, They're", example: "I'm hungry. She's nice. They're late.", he: 'בדיבור יומיומי משתמשים בקיצורים' },
    ],
    quiz: [
      { emoji:'😊', q:'I ___ happy.', opts:['am','is','are','be'], ans:'am' },
      { emoji:'👦', q:'He ___ my friend.', opts:['am','is','are','be'], ans:'is' },
      { emoji:'🐱', q:'The cat ___ small.', opts:['am','is','are','be'], ans:'is' },
      { emoji:'👧👦', q:'We ___ students.', opts:['am','is','are','be'], ans:'are' },
      { emoji:'🌍', q:'They ___ from Israel.', opts:['am','is','are','be'], ans:'are' },
      { emoji:'🌤️', q:'It ___ sunny today.', opts:['am','is','are','be'], ans:'is' },
      { emoji:'👩', q:'She ___ a teacher.', opts:['am','is','are','be'], ans:'is' },
      { emoji:'🧒', q:'You ___ very smart.', opts:['am','is','are','be'], ans:'are' },
    ]
  },
  {
    id: 'plural',
    emoji: '📝',
    color: '#E91E63',
    title: 'יחיד ורבים',
    explanation: [
      { rule: 'רוב המילים: + s', example: 'cat → cats,  dog → dogs,  book → books', he: 'רוב המילים — פשוט מוסיפים s' },
      { rule: 'אחרי s / x / ch / sh: + es', example: 'bus → buses,  box → boxes,  church → churches', he: 'אחרי s, x, ch, sh — מוסיפים es' },
      { rule: 'מסתיים ב-y: y → ies', example: 'baby → babies,  city → cities', he: 'כשנגמר ב-y אחרי עיצור — y הופך ies' },
      { rule: 'מסתיים ב-f/fe: → ves', example: 'leaf → leaves,  knife → knives', he: 'כשנגמר ב-f או fe — הופך ves' },
      { rule: 'לא-רגולריים (ללמוד בעל-פה)', example: 'child → children,  mouse → mice,  person → people,  tooth → teeth', he: 'כמה מילים נפוצות משנות צורה לגמרי!' },
    ],
    quiz: [
      { emoji:'🐱', q:'One cat → Two ___', opts:['cats','cates','catses','kittens'], ans:'cats' },
      { emoji:'🚌', q:'One bus → Two ___', opts:['bus','buses','buss','busi'], ans:'buses' },
      { emoji:'👶', q:'One baby → Two ___', opts:['babys','babies','babes','babyes'], ans:'babies' },
      { emoji:'🍃', q:'One leaf → Many ___', opts:['leafs','leaves','leafes','leavs'], ans:'leaves' },
      { emoji:'🧒', q:'One child → Many ___', opts:['childs','childes','children','childrens'], ans:'children' },
      { emoji:'🐭', q:'One mouse → Two ___', opts:['mouses','mouse','mice','micees'], ans:'mice' },
      { emoji:'📦', q:'One box → Two ___', opts:['boxs','box','boxies','boxes'], ans:'boxes' },
      { emoji:'🏙️', q:'One city → Two ___', opts:['citys','cities','cityes','citys'], ans:'cities' },
    ]
  },
  {
    id: 'articles',
    emoji: '🔵',
    color: '#1565C0',
    title: 'a, an, the',
    explanation: [
      { rule: '"a" — לפני עיצור', example: 'a cat,  a dog,  a big house,  a book', he: 'כשהמילה הבאה מתחילה בעיצור — משתמשים ב-a' },
      { rule: '"an" — לפני תנועה (a, e, i, o, u)', example: 'an apple,  an elephant,  an orange,  an ice cream', he: 'כשהמילה הבאה מתחילה בתנועה — משתמשים ב-an' },
      { rule: '"the" — כשמדברים על משהו ספציפי', example: 'The cat is black. Pass me the book, please.', he: 'כבר מכירים / ספציפי — משתמשים ב-the' },
      { rule: '"the" — יחיד בעולם', example: 'The sun, the moon, the sea, the sky', he: 'דברים יחידניים בעולם — תמיד the' },
    ],
    quiz: [
      { emoji:'🐘', q:'I saw ___ elephant at the zoo.', opts:['a','an','the','—'], ans:'an' },
      { emoji:'🌞', q:'___ sun is very bright.', opts:['A','An','The','—'], ans:'The' },
      { emoji:'🐶', q:'She has ___ dog.', opts:['a','an','the','—'], ans:'a' },
      { emoji:'🍎', q:'He ate ___ apple.', opts:['a','an','the','—'], ans:'an' },
      { emoji:'📚', q:'___ book on the table is mine.', opts:['A','An','The','—'], ans:'The' },
      { emoji:'🚗', q:'I want to buy ___ car.', opts:['a','an','the','—'], ans:'a' },
      { emoji:'🌍', q:'___ Earth goes around the sun.', opts:['A','An','The','—'], ans:'The' },
      { emoji:'🦉', q:'There is ___ owl in the tree.', opts:['a','an','the','—'], ans:'an' },
    ]
  },
  {
    id: 'adjectives',
    emoji: '🎨',
    color: '#FF6F00',
    title: 'שמות תואר',
    explanation: [
      { rule: 'שם תואר בא לפני שם העצם', example: 'a big dog,  a red apple,  a happy girl', he: 'בניגוד לעברית — באנגלית שם התואר קודם!' },
      { rule: 'שם תואר אחרי to be', example: 'The dog is big.  She is happy.  They are tired.', he: 'שם תואר יכול לבוא גם אחרי is / are / am' },
      { rule: 'השוואה: + er (מילה קצרה)', example: 'big → bigger,  tall → taller,  fast → faster', he: 'להשוות מילים קצרות — מוסיפים -er' },
      { rule: 'השוואה: more (מילה ארוכה)', example: 'beautiful → more beautiful,  expensive → more expensive', he: 'מילות תואר ארוכות — משתמשים ב-more' },
      { rule: 'עליון: + est / most', example: 'big → the biggest,  happy → the happiest,  beautiful → the most beautiful', he: '"הכי..." — est לקצרות, most לארוכות' },
    ],
    quiz: [
      { emoji:'🐘', q:'The elephant is very ___.', opts:['big','bigging','biggest','more big'], ans:'big' },
      { emoji:'🌈', q:'Choose the adjective:', opts:['run','beautiful','eat','quickly'], ans:'beautiful' },
      { emoji:'🦁', q:'A lion is ___ than a cat.', opts:['big','bigger','most big','bigest'], ans:'bigger' },
      { emoji:'⭐', q:'She is the ___ student in the class.', opts:['smart','smarter','most smart','smartest'], ans:'smartest' },
      { emoji:'🎈', q:'The balloon is ___.', opts:['fly','red','redly','redding'], ans:'red' },
      { emoji:'😊', q:'He is ___ than his brother.', opts:['happy','happier','happiest','more happy'], ans:'happier' },
      { emoji:'🌺', q:'This flower is the ___ in the garden.', opts:['beautiful','more beautiful','most beautiful','beautifulest'], ans:'most beautiful' },
    ]
  },
  {
    id: 'present_simple',
    emoji: '⚡',
    color: '#00897B',
    title: 'הווה פשוט',
    explanation: [
      { rule: 'I / You / We / They + פועל רגיל', example: 'I eat pizza.  You play football.  They run fast.', he: 'עם I, You, We, They — הפועל לא משתנה' },
      { rule: 'He / She / It + פועל + s', example: 'He eats pizza.  She plays football.  It runs fast.', he: 'עם He, She, It — מוסיפים s לפועל' },
      { rule: 'פעלים מיוחדים: do/go/have → does/goes/has', example: 'She does her homework.  He goes to school.  It has a tail.', he: 'כמה פעלים נפוצים משנים צורה ב-he/she/it' },
      { rule: 'שלילה: do not / does not', example: 'I do not eat meat.  She does not play games.', he: 'שלילה: do not (I/You/We/They) / does not (He/She/It)' },
      { rule: 'שאלה: Do / Does', example: 'Do you like pizza?  Does she know?', he: 'שאלה: Do (I/You/We/They) / Does (He/She/It)' },
    ],
    quiz: [
      { emoji:'🍕', q:'She ___ pizza every day.', opts:['eat','eats','eating','eaten'], ans:'eats' },
      { emoji:'⚽', q:'They ___ football on Fridays.', opts:['play','plays','playing','played'], ans:'play' },
      { emoji:'🐕', q:'The dog ___ a lot.', opts:['bark','barks','barking','barked'], ans:'barks' },
      { emoji:'📚', q:'We ___ books at school.', opts:['read','reads','reading','readed'], ans:'read' },
      { emoji:'🌙', q:'He ___ early every night.', opts:['sleep','sleeps','sleeping','slept'], ans:'sleeps' },
      { emoji:'🐱', q:'My cat ___ fish.', opts:['like','likes','liking','liked'], ans:'likes' },
      { emoji:'🎒', q:'___ you go to school every day?', opts:['Do','Does','Did','Are'], ans:'Do' },
    ]
  },
  {
    id: 'present_continuous',
    emoji: '🔄',
    color: '#43A047',
    title: 'הווה מתמשך',
    explanation: [
      { rule: 'am / is / are + פועל + ing', example: 'I am eating.  She is playing.  They are running.', he: 'to be + פועל עם סיומת ing — לפעולה שקורה עכשיו' },
      { rule: 'מתי משתמשים?', example: 'Look! The dog is running!  I am studying right now.', he: 'לפעולה שמתרחשת ברגע זה — עכשיו, עכשיו!' },
      { rule: 'כפילות עיצור (CVC קצר)', example: 'run → running,  sit → sitting,  swim → swimming', he: 'פועל קצר שנגמר בתנועה + עיצור — כפל את האות האחרונה' },
      { rule: 'מסתיים ב-e — הסר את ה-e', example: 'make → making,  ride → riding,  write → writing', he: 'פועל שנגמר ב-e — מסירים ה-e ואז מוסיפים ing' },
    ],
    quiz: [
      { emoji:'🏃', q:'She ___ in the park right now.', opts:['run','runs','is running','running'], ans:'is running' },
      { emoji:'📖', q:'They ___ their homework now.', opts:['do','does','are doing','doing'], ans:'are doing' },
      { emoji:'🍳', q:'Mum ___ dinner at the moment.', opts:['cook','cooks','is cooking','cooking'], ans:'is cooking' },
      { emoji:'😴', q:'The baby ___ right now.', opts:['sleep','sleeps','is sleeping','sleeping'], ans:'is sleeping' },
      { emoji:'🎮', q:'I ___ a video game right now.', opts:['play','plays','am playing','playing'], ans:'am playing' },
      { emoji:'✍️', q:'"sit" + ing = ?', opts:['siting','sitting','siteing','sitteing'], ans:'sitting' },
      { emoji:'🚴', q:'"ride" + ing = ?', opts:['rideing','ridding','riding','rideing'], ans:'riding' },
    ]
  },
  {
    id: 'past_simple',
    emoji: '⏰',
    color: '#6D4C41',
    title: 'עבר פשוט',
    explanation: [
      { rule: 'פעלים רגולריים: + ed', example: 'play → played,  walk → walked,  watch → watched', he: 'רוב הפעלים — מוסיפים ed' },
      { rule: 'מסתיים ב-e: + d בלבד', example: 'like → liked,  live → lived,  dance → danced', he: 'כשנגמר ב-e — מוסיפים רק d' },
      { rule: 'פעלים לא-רגולריים נפוצים', example: 'go → went,  eat → ate,  see → saw,  come → came,  have → had,  make → made', he: 'הפעלים הנפוצים ביותר — חובה לשנן!' },
      { rule: 'שלילה: did not (לכולם)', example: 'I did not go.  She did not eat.  They did not come.', he: 'שלילה: did not + פועל בסיסי — לכולם אותו דבר' },
      { rule: 'שאלה: Did (לכולם)', example: 'Did you go?  Did she eat?  Did they win?', he: 'שאלה: Did + פועל בסיסי — לכולם אותו דבר' },
    ],
    quiz: [
      { emoji:'⚽', q:'Yesterday, he ___ football.', opts:['play','plays','playing','played'], ans:'played' },
      { emoji:'🚶', q:'We ___ to school this morning.', opts:['go','goes','went','gone'], ans:'went' },
      { emoji:'🍕', q:'She ___ pizza for lunch.', opts:['eat','eats','eating','ate'], ans:'ate' },
      { emoji:'👀', q:'I ___ a rainbow yesterday.', opts:['see','sees','saw','seen'], ans:'saw' },
      { emoji:'📺', q:'They ___ a film last night.', opts:['watch','watches','watching','watched'], ans:'watched' },
      { emoji:'🛌', q:'The baby ___ for 10 hours.', opts:['sleep','sleeps','slept','sleeping'], ans:'slept' },
      { emoji:'🙅', q:'___ she come to the party?', opts:['Do','Does','Did','Was'], ans:'Did' },
    ]
  },
  {
    id: 'future_will',
    emoji: '🚀',
    color: '#1976D2',
    title: "עתיד עם 'will'",
    explanation: [
      { rule: 'will + פועל בסיסי — לכולם!', example: 'I will go.  She will eat.  They will play.  He will come.', he: 'will + פועל — אותו דבר לכל הגופים, ללא שינוי!' },
      { rule: "קיצור: 'll", example: "I'll go.  She'll eat.  They'll come.  We'll win!", he: "בדיבור יומיומי — 'll במקום will" },
      { rule: "שלילה: will not / won't", example: "I won't go.  She will not eat.  They won't come.", he: "שלילה: will not = won't" },
      { rule: 'שאלה: Will + נושא + פועל?', example: 'Will you come?  Will she help?  Will it rain?', he: 'שאלה — Will קודם לנושא' },
    ],
    quiz: [
      { emoji:'☀️', q:'Tomorrow it ___ sunny.', opts:['is','was','will be','being'], ans:'will be' },
      { emoji:'🎂', q:'She ___ 10 years old next week.', opts:['is','was','will be','been'], ans:'will be' },
      { emoji:'✈️', q:'We ___ to London next year.', opts:['go','went','will go','going'], ans:'will go' },
      { emoji:'📚', q:'He ___ hard for the test.', opts:['study','studied','will study','studying'], ans:'will study' },
      { emoji:'🌧️', q:'I think it ___ rain today.', opts:['is','was','will','wills'], ans:'will' },
      { emoji:'🤝', q:'___ you help me, please?', opts:['Do','Did','Will','Are'], ans:'Will' },
      { emoji:'🏆', q:"___ they win the match?", opts:['Do','Did','Will','Are'], ans:'Will' },
    ]
  },
];
